language: node_js

services:
- docker

before_install:
- docker build -t thomas/node-web-app .
- docker run  -p 3000:3000 -d thomas/node-web-app

script:
- npm install 

after_success:
- pip install --user awscli
- eval $(aws ecr get-login --no-include-email --region eu-west-1)
- docker build -t thomas/node-web-app
- docker tag thomas/node-web-app:latest 941133175822.dkr.ecr.eu-west-1.amazonaws.com/isentest:latest
- docker push 941133175822.dkr.ecr.eu-west-1.amazonaws.com/isentest:latest